pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            steps {
                echo ''
                dir('bugtracker-backend') {
                    go test -v ./...
                }
            }
        }
    }
}