pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = "${WORKSPACE}/.cache/go-build"
                GOPATH = "${WORKSPACE}/.go"
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}